# Знакомство с PyTorch

Сейчас мы познакомимся с библиотекой *PyTorch*. Он очень похож на *NumPy*, и сейчас вы в этом убедитесь!

А почему именно *PyTorch*? Почитать можно [здесь](https://habr.com/ru/post/334380/).

## Вспоминаем *NumPy* и сравниваем операции в *PyTorch*

Мы можем создавать матрицы, перемножать их, складывать, транспонировать и в целом совершать любые матричные операции

In [ ]:
import numpy as np 

import torch
import torchvision

import torch.nn as nn
import torch.nn.functional as F

import matplotlib.pyplot as plt

In [ ]:
np.random.seed(42)

a = np.random.rand(5, 3) # создали случайную матрицу 
a

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [ ]:
print("Проверили размеры : %s\n" % (a.shape,))

Проверили размеры : (5, 3)



In [ ]:
print("Добавили 5 :\n%s\n" % (a + 5))

Добавили 5 :
[[5.37454012 5.95071431 5.73199394]
 [5.59865848 5.15601864 5.15599452]
 [5.05808361 5.86617615 5.60111501]
 [5.70807258 5.02058449 5.96990985]
 [5.83244264 5.21233911 5.18182497]]



## Задание

Умножьте матрицу `а` на транспонированную матрицу `а`.  

Чему равен самый первый элемент результата?  
Ответ округлите до сотых.

In [ ]:
# your code here

In [ ]:
print("Среднее по колонкам :\n%s\n" % (a.mean(axis=-1)))

Среднее по колонкам :
[0.68574946 0.30355721 0.50845826 0.56618897 0.40886891]



In [ ]:
print("Изменили размеры :\n%s\n" % (a.reshape(3, 5).shape,))

Изменили размеры :
(3, 5)



## Задание

При помощи *NumPy* посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [ ]:
# your code here

Аналогичные операции в *PyTorch* выглядят следующим образом, синтаксис отличается, но совсем немного:

In [ ]:
x = torch.rand(5, 3)
x

tensor([[7.3177e-01, 2.5917e-01, 9.9112e-01],
        [3.8936e-01, 4.0239e-01, 3.5546e-01],
        [8.3254e-01, 2.9720e-01, 5.2920e-01],
        [3.9288e-01, 2.0885e-04, 9.4136e-02],
        [4.3311e-01, 6.4902e-01, 4.8439e-02]])

In [ ]:
print("Проверили размеры : %s\n" % (x.shape,))

Проверили размеры : torch.Size([5, 3])



In [ ]:
print("Добавили 5 :\n%s\n" % (x + 5))

Добавили 5 :
tensor([[5.7318, 5.2592, 5.9911],
        [5.3894, 5.4024, 5.3555],
        [5.8325, 5.2972, 5.5292],
        [5.3929, 5.0002, 5.0941],
        [5.4331, 5.6490, 5.0484]])



In [ ]:
print("X*X^T  (1):\n%s\n" % (torch.matmul(x, x.transpose(1, 0))))
print("X*X^T  (2):\n%s\n" % (x.mm(x.t())))

X*X^T  (1):
tensor([[1.5850, 0.7415, 1.2107, 0.3809, 0.5332],
        [0.7415, 0.4399, 0.6319, 0.1865, 0.4470],
        [1.2107, 0.6319, 1.0615, 0.3770, 0.5791],
        [0.3809, 0.1865, 0.3770, 0.1632, 0.1749],
        [0.5332, 0.4470, 0.5791, 0.1749, 0.6112]])

X*X^T  (2):
tensor([[1.5850, 0.7415, 1.2107, 0.3809, 0.5332],
        [0.7415, 0.4399, 0.6319, 0.1865, 0.4470],
        [1.2107, 0.6319, 1.0615, 0.3770, 0.5791],
        [0.3809, 0.1865, 0.3770, 0.1632, 0.1749],
        [0.5332, 0.4470, 0.5791, 0.1749, 0.6112]])



In [ ]:
print("Среднее по колонкам :\n%s\n" % (x.mean(dim=-1)))

Среднее по колонкам :
tensor([0.6607, 0.3824, 0.5530, 0.1624, 0.3769])



In [ ]:
print("Изменили размеры :\n%s\n" % (x.view([3, 5]).shape,))
print("Изменили размеры :\n%s\n" % (x.view_as(x.t()).shape,))

Изменили размеры :
torch.Size([3, 5])

Изменили размеры :
torch.Size([3, 5])



Небольшой пример того, как меняются операции:

* `x.reshape([1,2,8]) -> x.view(1,2,8)`

* `x.sum(axis=-1) -> x.sum(dim=-1)`

* `x.astype('int64') -> x.type(torch.LongTensor)`

Для помощи вам есть [таблица](https://github.com/torch/torch7/wiki/Torch-for-Numpy-users), которая поможет вам найти аналог операции в *NumPy*.


При помощи *PyTorch* посчитаем сумму квадратов натуральных чисел от 1 до 10000.

In [ ]:
torch.sum(torch.range(1, 10000) ** 2)

<ipython-input-15-b9d129fd8adb>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.sum(torch.range(1, 10000) ** 2)


tensor(3.3338e+11)

Создаем тензоры в *PyTorch* и снова изучаем базовые операции

In [ ]:
x = torch.empty(5, 3) # пустой тензор
print(x)

tensor([[7.0251e-34, 0.0000e+00, 3.5032e-44],
        [0.0000e+00,        nan, 2.3694e-38],
        [1.1578e+27, 7.1463e+22, 4.6241e+30],
        [1.0552e+24, 5.5757e-02, 1.8728e+31],
        [5.9571e-02, 7.0374e+22, 3.4548e-09]])


In [ ]:
x = torch.rand(5, 3) # тензор со случайными числами
print(x)

tensor([[0.6397, 0.0819, 0.0936],
        [0.3876, 0.8394, 0.1254],
        [0.4246, 0.2452, 0.7437],
        [0.6118, 0.9102, 0.8507],
        [0.8313, 0.8549, 0.7527]])


In [ ]:
x = torch.zeros(5, 3, dtype=torch.long) # тензор с нулями и указанием типов чисел
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
x = torch.tensor([5.5, 3]) # конструируем тензор из питоновского листа
print(x)

tensor([5.5000, 3.0000])


In [ ]:
x = x.new_ones(5, 3, dtype=torch.double) # используем уже созданный тензор для создания тензора из единичек
print(x, x.size()) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) torch.Size([5, 3])


In [ ]:
x = torch.randn_like(x, dtype=torch.float) # создаем матрицу с размерами как у x
print(x, x.size())

tensor([[ 0.4919,  1.2069,  0.9834],
        [ 2.4226, -0.9138,  1.8904],
        [-0.4267, -1.5911, -1.0336],
        [ 1.5065,  1.1856,  0.0405],
        [-0.4549,  0.1618, -1.0552]]) torch.Size([5, 3])


## Задание

Сгенерируйте два тензора: `x` и `y` размера 5 на 3 со случайными числами.
Вычислите сумму тензоров `x` и `y`.

В ответе напишите значение первой координаты в полученной суммы, округленной до сотых.

In [ ]:
torch.manual_seed(42)

# your code here

In [ ]:
print(x * y) # поэлементное умножение

## Задание

Умножьте матрицу `x` на транспонированную матрицу `y`.

В ответ напишите последний элемент (правый нижний) полученной матрицы.  
Ответ округлите до сотых.

In [ ]:
# your code here

In [ ]:
print(x.unsqueeze(0).shape) # добавили измерение в начало, аналог броадкастинга 

torch.Size([1, 5, 3])


In [ ]:
print(x.unsqueeze(0).squeeze(0).shape) # убрали измерение в начале, аналог броадкастинга 

torch.Size([5, 3])


In [ ]:
a = torch.rand((1,3))
a

tensor([[0.8823, 0.9150, 0.3829]])

In [ ]:
a.squeeze(0)

tensor([0.8823, 0.9150, 0.3829])

Мы также можем делать обычные срезы и переводить матрицы назад в *NumPy*:

In [ ]:
a = np.ones((3, 5))
x = torch.ones((3, 5))
print(np.allclose(x.numpy(), a))
print(np.allclose(x.numpy()[:, 1], a[:, 1]))

True
True


In [ ]:
a = np.array([1,2,3,4])
b = np.array([[5],[6],[7],[8]])

a.shape, b.shape

((4,), (4, 1))

In [ ]:
a @ b

array([70])

In [ ]:
b @ a

ValueError: ignored