# Знакомство с PyTorch

Сейчас мы познакомимся с библиотекой *PyTorch*. Он очень похож на *NumPy*, и сейчас вы в этом убедитесь!

А почему именно *PyTorch*? Почитать можно [здесь](https://habr.com/ru/post/334380/).

## Вспоминаем *NumPy* и сравниваем операции в *PyTorch*

Мы можем создавать матрицы, перемножать их, складывать, транспонировать и в целом совершать любые матричные операции

In [1]:
import numpy as np 

import torch
import torchvision

import torch.nn as nn
import torch.nn.functional as F

import matplotlib.pyplot as plt

In [2]:
np.random.seed(42)

a = np.random.rand(5, 3) # создали случайную матрицу 

In [3]:
print("Проверили размеры : %s\n" % (a.shape,))

Проверили размеры : (5, 3)



In [4]:
print("Добавили 5 :\n%s\n" % (a + 5))

Добавили 5 :
[[5.37454012 5.95071431 5.73199394]
 [5.59865848 5.15601864 5.15599452]
 [5.05808361 5.86617615 5.60111501]
 [5.70807258 5.02058449 5.96990985]
 [5.83244264 5.21233911 5.18182497]]



## Задание

Умножьте матрицу `а` на транспонированную матрицу `а`.  

Чему равен самый первый элемент результата?  
Ответ округлите до сотых.

In [5]:
# your code here
round((a @ a.T)[0, 0], 2)

1.58

In [6]:
print("Среднее по колонкам :\n%s\n" % (a.mean(axis=-1)))

Среднее по колонкам :
[0.68574946 0.30355721 0.50845826 0.56618897 0.40886891]



In [7]:
print("Изменили размеры :\n%s\n" % (a.reshape(3, 5).shape,))

Изменили размеры :
(3, 5)



## Задание

При помощи *NumPy* посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [8]:
# your code here
a = np.linspace(1, 10_000, 10_000)
np.sum(a*a)

333383335000.0

Аналогичные операции в *PyTorch* выглядят следующим образом, синтаксис отличается, но совсем немного:

In [9]:
x = torch.rand(5, 3)
x

tensor([[0.3579, 0.0989, 0.3684],
        [0.9048, 0.1367, 0.6982],
        [0.7470, 0.3136, 0.2804],
        [0.5586, 0.8997, 0.3720],
        [0.8816, 0.3273, 0.3681]])

In [10]:
print("Проверили размеры : %s\n" % (x.shape,))

Проверили размеры : torch.Size([5, 3])



In [11]:
print("Добавили 5 :\n%s\n" % (x + 5))

Добавили 5 :
tensor([[5.3579, 5.0989, 5.3684],
        [5.9048, 5.1367, 5.6982],
        [5.7470, 5.3136, 5.2804],
        [5.5586, 5.8997, 5.3720],
        [5.8816, 5.3273, 5.3681]])



In [12]:
print("X*X^T  (1):\n%s\n" % (torch.matmul(x, x.transpose(1, 0))))
print("X*X^T  (2):\n%s\n" % (x.mm(x.t())))

X*X^T  (1):
tensor([[0.2736, 0.5946, 0.4017, 0.4259, 0.4835],
        [0.5946, 1.3249, 0.9146, 0.8882, 1.0995],
        [0.4017, 0.9146, 0.7350, 0.8038, 0.8644],
        [0.4259, 0.8882, 0.8038, 1.2599, 0.9239],
        [0.4835, 1.0995, 0.8644, 0.9239, 1.0198]])

X*X^T  (2):
tensor([[0.2736, 0.5946, 0.4017, 0.4259, 0.4835],
        [0.5946, 1.3249, 0.9146, 0.8882, 1.0995],
        [0.4017, 0.9146, 0.7350, 0.8038, 0.8644],
        [0.4259, 0.8882, 0.8038, 1.2599, 0.9239],
        [0.4835, 1.0995, 0.8644, 0.9239, 1.0198]])



In [13]:
print("Среднее по колонкам :\n%s\n" % (x.mean(dim=-1)))

Среднее по колонкам :
tensor([0.2751, 0.5799, 0.4470, 0.6101, 0.5257])



In [14]:
print("Изменили размеры :\n%s\n" % (x.view([3, 5]).shape,))
print("Изменили размеры :\n%s\n" % (x.view_as(x.t()).shape,))

Изменили размеры :
torch.Size([3, 5])

Изменили размеры :
torch.Size([3, 5])



Небольшой пример того, как меняются операции:

* `x.reshape([1,2,8]) -> x.view(1,2,8)`

* `x.sum(axis=-1) -> x.sum(dim=-1)`

* `x.astype('int64') -> x.type(torch.LongTensor)`

Для помощи вам есть [таблица](https://github.com/torch/torch7/wiki/Torch-for-Numpy-users), которая поможет вам найти аналог операции в *NumPy*.


При помощи *PyTorch* посчитаем сумму квадратов натуральных чисел от 1 до 10000.

In [15]:
torch.sum(torch.range(1, 10000) ** 2)

<ipython-input-15-b9d129fd8adb>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.sum(torch.range(1, 10000) ** 2)


tensor(3.3338e+11)

Создаем тензоры в *PyTorch* и снова изучаем базовые операции

In [16]:
x = torch.empty(5, 3) # пустой тензор
print(x)

tensor([[2.1917e+27, 4.5747e-41, 1.3516e-34],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 7.7052e+31, 7.2148e+22],
        [1.5766e-19, 1.0256e-08, 1.0255e-08]])


In [17]:
x = torch.rand(5, 3) # тензор со случайными числами
print(x)

tensor([[0.1212, 0.2491, 0.0079],
        [0.0436, 0.5557, 0.1318],
        [0.7109, 0.0437, 0.4114],
        [0.1925, 0.1125, 0.9011],
        [0.5026, 0.4141, 0.4882]])


In [18]:
x = torch.zeros(5, 3, dtype=torch.long) # тензор с нулями и указанием типов чисел
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [19]:
x = torch.tensor([5.5, 3]) # конструируем тензор из питоновского листа
print(x)

tensor([5.5000, 3.0000])


In [20]:
x = x.new_ones(5, 3, dtype=torch.double) # используем уже созданный тензор для создания тензора из единичек
print(x, x.size()) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) torch.Size([5, 3])


In [21]:
x = torch.randn_like(x, dtype=torch.float) # создаем матрицу с размерами как у x
print(x, x.size())

tensor([[-1.6983,  0.0249, -2.1670],
        [ 1.2955,  0.3561,  0.4395],
        [ 0.5696,  0.3200, -1.0478],
        [ 0.3721,  1.1459,  0.7173],
        [-1.5992,  0.9534, -0.3797]]) torch.Size([5, 3])


## Задание

Сгенерируйте два тензора: `x` и `y` размера 5 на 3 со случайными числами.
Вычислите сумму тензоров `x` и `y`.

В ответе напишите значение первой координаты в полученной суммы, округленной до сотых.

In [24]:
torch.manual_seed(42)

# your code here
x = torch.rand(5, 3)
y = torch.rand(5, 3)

In [27]:
# print(x * y) # поэлементное умножение
print(x + y)

tensor([[1.3117, 1.8004, 0.9568],
        [1.2259, 1.0179, 0.8705],
        [0.6979, 1.0906, 1.7725],
        [0.2385, 1.2041, 0.9524],
        [1.0688, 1.1149, 0.7473]])


## Задание

Умножьте матрицу `x` на транспонированную матрицу `y`.

В ответ напишите последний элемент (правый нижний) полученной матрицы.  
Ответ округлите до сотых.

In [39]:
# your code here
res = x @ y.T
torch.round(res[res.shape[0]-1, res.shape[1]-1], decimals=2)

tensor(0.4900)

In [40]:
print(x.unsqueeze(0).shape) # добавили измерение в начало, аналог броадкастинга 

torch.Size([1, 5, 3])


In [41]:
print(x.unsqueeze(0).squeeze(0).shape) # убрали измерение в начале, аналог броадкастинга 

torch.Size([5, 3])


In [42]:
a = torch.rand((1,3))
a

tensor([[0.9516, 0.0753, 0.8860]])

In [43]:
a.squeeze(0)

tensor([0.9516, 0.0753, 0.8860])

Мы также можем делать обычные срезы и переводить матрицы назад в *NumPy*:

In [44]:
a = np.ones((3, 5))
x = torch.ones((3, 5))
print(np.allclose(x.numpy(), a))
print(np.allclose(x.numpy()[:, 1], a[:, 1]))

True
True


In [45]:
a = np.array([1,2,3,4])
b = np.array([[5],[6],[7],[8]])

a.shape, b.shape

((4,), (4, 1))

In [46]:
a @ b

array([70])

In [48]:
# b @ a
# Error